name: Scala PR format CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run sbt format
      run: sbt scalafmtAll
    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Apply scalafmt Change
        ref: ${{ github.head_ref }}
